const actionsTypes = {
    FETCH_USERS_BEGIN: 'FETCH_USERS_BEGIN',
    FETCH_USERS_SUCCESS: 'FETCH_USERS_SUCCESS',
    FETCH_USERS_ERROR: 'FETCH_USERS_ERROR',

    FETCH_USERS_BY_REGION_BEGIN: 'FETCH_USERS_BY_REGION_BEGIN',
    FETCH_USERS_BY_REGION_SUCCESS: 'FETCH_USERS_BY_REGION_SUCCESS',
    FETCH_USERS_BY_REGION_ERROR: 'FETCH_USERS_BY_REGION_ERROR',

    FETCH_REGIONS_BEGIN: 'FETCH_REGIONS_BEGIN',
    FETCH_REGIONS_SUCCESS: 'FETCH_REGIONS_SUCCESS',
    FETCH_REGIONS_ERROR: 'FETCH_REGIONS_ERROR',
};

export default actionsTypes;
